# Generated by Django 5.1.5 on 2025-01-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
